// ============================================================================
// WEDINVITER pSEO — Seed Database Script
// Run: npx tsx scripts/pseo/seed-database.ts
// Seeds: 136 locations, 12 topics, 240 subtopics, then generates 50K+ queue
// ============================================================================

import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

// ============================================================================
// LOCATION DATA — 136 entries (28 states + 8 UTs + 100 cities)
// ============================================================================

const TIER_1_CITIES = [
  {
    name: "Mumbai",
    slug: "mumbai",
    state: "Maharashtra",
    region: "west",
    population: 12478447,
    volume: 12000,
    priority: 100,
    tier: 1,
    tags: ["hindu", "muslim", "christian", "parsi", "jain"],
    lat: 19.076,
    lng: 72.8777,
  },
  {
    name: "Delhi NCR",
    slug: "delhi-ncr",
    state: "Delhi",
    region: "north",
    population: 11007835,
    volume: 15000,
    priority: 100,
    tier: 1,
    tags: ["hindu", "muslim", "sikh", "christian", "jain"],
    lat: 28.7041,
    lng: 77.1025,
  },
  {
    name: "Bengaluru",
    slug: "bengaluru",
    state: "Karnataka",
    region: "south",
    population: 8443675,
    volume: 10000,
    priority: 100,
    tier: 1,
    tags: ["hindu", "muslim", "christian"],
    lat: 12.9716,
    lng: 77.5946,
  },
  {
    name: "Hyderabad",
    slug: "hyderabad",
    state: "Telangana",
    region: "south",
    population: 6809970,
    volume: 9000,
    priority: 100,
    tier: 1,
    tags: ["hindu", "muslim"],
    lat: 17.385,
    lng: 78.4867,
  },
  {
    name: "Chennai",
    slug: "chennai",
    state: "Tamil Nadu",
    region: "south",
    population: 7088000,
    volume: 8500,
    priority: 100,
    tier: 1,
    tags: ["hindu", "muslim", "christian"],
    lat: 13.0827,
    lng: 80.2707,
  },
  {
    name: "Kolkata",
    slug: "kolkata",
    state: "West Bengal",
    region: "east",
    population: 4496694,
    volume: 8000,
    priority: 100,
    tier: 1,
    tags: ["hindu", "muslim", "christian"],
    lat: 22.5726,
    lng: 88.3639,
  },
  {
    name: "Pune",
    slug: "pune",
    state: "Maharashtra",
    region: "west",
    population: 3124458,
    volume: 7500,
    priority: 100,
    tier: 1,
    tags: ["hindu", "muslim", "christian", "jain"],
    lat: 18.5204,
    lng: 73.8567,
  },
  {
    name: "Ahmedabad",
    slug: "ahmedabad",
    state: "Gujarat",
    region: "west",
    population: 5570585,
    volume: 7000,
    priority: 100,
    tier: 1,
    tags: ["hindu", "muslim", "jain"],
    lat: 23.0225,
    lng: 72.5714,
  },
  {
    name: "Kochi",
    slug: "kochi",
    state: "Kerala",
    region: "south",
    population: 2131000,
    volume: 6500,
    priority: 100,
    tier: 1,
    tags: ["hindu", "christian", "muslim"],
    lat: 9.9312,
    lng: 76.2673,
  },
  {
    name: "Thrissur",
    slug: "thrissur",
    state: "Kerala",
    region: "south",
    population: 1850000,
    volume: 6000,
    priority: 100,
    tier: 1,
    tags: ["hindu", "christian", "muslim"],
    lat: 10.5276,
    lng: 76.2144,
  },
  {
    name: "Trivandrum",
    slug: "trivandrum",
    state: "Kerala",
    region: "south",
    population: 1680000,
    volume: 5800,
    priority: 100,
    tier: 1,
    tags: ["hindu", "christian", "muslim"],
    lat: 8.5241,
    lng: 76.9366,
  },
  {
    name: "Kozhikode",
    slug: "kozhikode",
    state: "Kerala",
    region: "south",
    population: 2050000,
    volume: 5500,
    priority: 100,
    tier: 1,
    tags: ["hindu", "muslim", "christian"],
    lat: 11.2588,
    lng: 75.7804,
  },
  {
    name: "Ernakulam",
    slug: "ernakulam",
    state: "Kerala",
    region: "south",
    population: 1100000,
    volume: 5000,
    priority: 100,
    tier: 1,
    tags: ["hindu", "christian", "muslim"],
    lat: 9.9816,
    lng: 76.2998,
  },
  {
    name: "Kannur",
    slug: "kannur",
    state: "Kerala",
    region: "south",
    population: 1250000,
    volume: 4800,
    priority: 100,
    tier: 1,
    tags: ["hindu", "muslim", "christian"],
    lat: 11.8745,
    lng: 75.3704,
  },
  {
    name: "Kollam",
    slug: "kollam",
    state: "Kerala",
    region: "south",
    population: 975000,
    volume: 4500,
    priority: 100,
    tier: 1,
    tags: ["hindu", "christian", "muslim"],
    lat: 8.8932,
    lng: 76.6141,
  },
  {
    name: "Alappuzha",
    slug: "alappuzha",
    state: "Kerala",
    region: "south",
    population: 870000,
    volume: 4200,
    priority: 100,
    tier: 1,
    tags: ["hindu", "christian", "muslim"],
    lat: 9.4981,
    lng: 76.3388,
  },
  {
    name: "Palakkad",
    slug: "palakkad",
    state: "Kerala",
    region: "south",
    population: 830000,
    volume: 4000,
    priority: 100,
    tier: 1,
    tags: ["hindu", "muslim", "christian"],
    lat: 10.7867,
    lng: 76.6548,
  },
  {
    name: "Malappuram",
    slug: "malappuram",
    state: "Kerala",
    region: "south",
    population: 1010000,
    volume: 3800,
    priority: 100,
    tier: 1,
    tags: ["muslim", "hindu", "christian"],
    lat: 11.051,
    lng: 76.0711,
  },
  {
    name: "Kasaragod",
    slug: "kasargod",
    state: "Kerala",
    region: "south",
    population: 700000,
    volume: 3500,
    priority: 100,
    tier: 1,
    tags: ["hindu", "muslim", "christian"],
    lat: 12.4994,
    lng: 74.9866,
  },
  {
    name: "Pathanamthitta",
    slug: "pathanamthitta",
    state: "Kerala",
    region: "south",
    population: 650000,
    volume: 3200,
    priority: 100,
    tier: 1,
    tags: ["hindu", "christian", "muslim"],
    lat: 9.2648,
    lng: 76.787,
  },
  {
    name: "Idukki",
    slug: "idukki",
    state: "Kerala",
    region: "south",
    population: 600000,
    volume: 3000,
    priority: 100,
    tier: 1,
    tags: ["hindu", "christian", "muslim"],
    lat: 9.8529,
    lng: 76.9994,
  },
];

const TIER_2_CITIES = [
  {
    name: "Jaipur",
    slug: "jaipur",
    state: "Rajasthan",
    region: "north",
    population: 3073350,
    volume: 5500,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim", "jain"],
    lat: 26.9124,
    lng: 75.7873,
  },
  {
    name: "Lucknow",
    slug: "lucknow",
    state: "Uttar Pradesh",
    region: "north",
    population: 2901474,
    volume: 5000,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim"],
    lat: 26.8467,
    lng: 80.9462,
  },
  {
    name: "Surat",
    slug: "surat",
    state: "Gujarat",
    region: "west",
    population: 4460002,
    volume: 4800,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim", "jain"],
    lat: 21.1702,
    lng: 72.8311,
  },
  {
    name: "Indore",
    slug: "indore",
    state: "Madhya Pradesh",
    region: "central",
    population: 1994397,
    volume: 4500,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim", "jain"],
    lat: 22.7196,
    lng: 75.8577,
  },
  {
    name: "Nagpur",
    slug: "nagpur",
    state: "Maharashtra",
    region: "west",
    population: 2405665,
    volume: 4200,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim", "buddhist"],
    lat: 21.1458,
    lng: 79.0882,
  },
  {
    name: "Visakhapatnam",
    slug: "visakhapatnam",
    state: "Andhra Pradesh",
    region: "south",
    population: 1728128,
    volume: 4000,
    priority: 75,
    tier: 2,
    tags: ["hindu", "christian", "muslim"],
    lat: 17.6868,
    lng: 83.2185,
  },
  {
    name: "Patna",
    slug: "patna",
    state: "Bihar",
    region: "east",
    population: 1684222,
    volume: 3800,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim"],
    lat: 25.5941,
    lng: 85.1376,
  },
  {
    name: "Vadodara",
    slug: "vadodara",
    state: "Gujarat",
    region: "west",
    population: 1753000,
    volume: 3600,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim", "jain"],
    lat: 22.3072,
    lng: 73.1812,
  },
  {
    name: "Ludhiana",
    slug: "ludhiana",
    state: "Punjab",
    region: "north",
    population: 1618879,
    volume: 3500,
    priority: 75,
    tier: 2,
    tags: ["sikh", "hindu", "muslim"],
    lat: 30.901,
    lng: 75.8573,
  },
  {
    name: "Coimbatore",
    slug: "coimbatore",
    state: "Tamil Nadu",
    region: "south",
    population: 1061110,
    volume: 3400,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim", "christian"],
    lat: 11.0168,
    lng: 76.9558,
  },
  {
    name: "Agra",
    slug: "agra",
    state: "Uttar Pradesh",
    region: "north",
    population: 1585704,
    volume: 3300,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim"],
    lat: 27.1767,
    lng: 78.0081,
  },
  {
    name: "Madurai",
    slug: "madurai",
    state: "Tamil Nadu",
    region: "south",
    population: 1017865,
    volume: 3200,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim", "christian"],
    lat: 9.9252,
    lng: 78.1198,
  },
  {
    name: "Nashik",
    slug: "nashik",
    state: "Maharashtra",
    region: "west",
    population: 1486053,
    volume: 3100,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim"],
    lat: 19.9975,
    lng: 73.7898,
  },
  {
    name: "Faridabad",
    slug: "faridabad",
    state: "Haryana",
    region: "north",
    population: 1404653,
    volume: 3000,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim", "sikh"],
    lat: 28.4089,
    lng: 77.3178,
  },
  {
    name: "Rajkot",
    slug: "rajkot",
    state: "Gujarat",
    region: "west",
    population: 1390000,
    volume: 2900,
    priority: 75,
    tier: 2,
    tags: ["hindu", "muslim", "jain"],
    lat: 22.3039,
    lng: 70.8022,
  },
];

const TIER_3_CITIES = [
  {
    name: "Meerut",
    slug: "meerut",
    state: "Uttar Pradesh",
    region: "north",
    population: 1305429,
    volume: 2500,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim"],
    lat: 28.9845,
    lng: 77.7064,
  },
  {
    name: "Varanasi",
    slug: "varanasi",
    state: "Uttar Pradesh",
    region: "north",
    population: 1198491,
    volume: 2800,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim"],
    lat: 25.3176,
    lng: 82.9739,
  },
  {
    name: "Srinagar",
    slug: "srinagar",
    state: "Jammu and Kashmir",
    region: "north",
    population: 1180570,
    volume: 2600,
    priority: 50,
    tier: 3,
    tags: ["muslim", "hindu"],
    lat: 34.0837,
    lng: 74.7973,
  },
  {
    name: "Amritsar",
    slug: "amritsar",
    state: "Punjab",
    region: "north",
    population: 1132383,
    volume: 2700,
    priority: 50,
    tier: 3,
    tags: ["sikh", "hindu", "muslim"],
    lat: 31.634,
    lng: 74.8723,
  },
  {
    name: "Aurangabad",
    slug: "aurangabad",
    state: "Maharashtra",
    region: "west",
    population: 1175116,
    volume: 2400,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim"],
    lat: 19.8762,
    lng: 75.3433,
  },
  {
    name: "Ranchi",
    slug: "ranchi",
    state: "Jharkhand",
    region: "east",
    population: 1073440,
    volume: 2300,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "christian"],
    lat: 23.3441,
    lng: 85.3096,
  },
  {
    name: "Jodhpur",
    slug: "jodhpur",
    state: "Rajasthan",
    region: "north",
    population: 1033918,
    volume: 2500,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "jain"],
    lat: 26.2389,
    lng: 73.0243,
  },
  {
    name: "Raipur",
    slug: "raipur",
    state: "Chhattisgarh",
    region: "central",
    population: 1010087,
    volume: 2200,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "christian"],
    lat: 21.2514,
    lng: 81.6296,
  },
  {
    name: "Kota",
    slug: "kota",
    state: "Rajasthan",
    region: "north",
    population: 1001694,
    volume: 2100,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim"],
    lat: 25.2138,
    lng: 75.8648,
  },
  {
    name: "Guwahati",
    slug: "guwahati",
    state: "Assam",
    region: "northeast",
    population: 968549,
    volume: 2400,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "christian"],
    lat: 26.1445,
    lng: 91.7362,
  },
  {
    name: "Chandigarh",
    slug: "chandigarh",
    state: "Chandigarh",
    region: "north",
    population: 1055450,
    volume: 2500,
    priority: 50,
    tier: 3,
    tags: ["hindu", "sikh", "muslim", "christian"],
    lat: 30.7333,
    lng: 76.7794,
  },
  {
    name: "Solapur",
    slug: "solapur",
    state: "Maharashtra",
    region: "west",
    population: 951558,
    volume: 2000,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim"],
    lat: 17.6599,
    lng: 75.9064,
  },
  {
    name: "Mysuru",
    slug: "mysuru",
    state: "Karnataka",
    region: "south",
    population: 887446,
    volume: 2200,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "christian"],
    lat: 12.2958,
    lng: 76.6394,
  },
  {
    name: "Tiruchirappalli",
    slug: "tiruchirappalli",
    state: "Tamil Nadu",
    region: "south",
    population: 847387,
    volume: 2100,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "christian"],
    lat: 10.7905,
    lng: 78.7047,
  },
  {
    name: "Gwalior",
    slug: "gwalior",
    state: "Madhya Pradesh",
    region: "central",
    population: 1054520,
    volume: 2000,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "jain"],
    lat: 26.2183,
    lng: 78.1828,
  },
  {
    name: "Jabalpur",
    slug: "jabalpur",
    state: "Madhya Pradesh",
    region: "central",
    population: 1067000,
    volume: 1900,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim"],
    lat: 23.1815,
    lng: 79.9864,
  },
  {
    name: "Vijayawada",
    slug: "vijayawada",
    state: "Andhra Pradesh",
    region: "south",
    population: 1048240,
    volume: 2300,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "christian"],
    lat: 16.5062,
    lng: 80.648,
  },
  {
    name: "Bhopal",
    slug: "bhopal",
    state: "Madhya Pradesh",
    region: "central",
    population: 1798218,
    volume: 2800,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim"],
    lat: 23.2599,
    lng: 77.4126,
  },
  {
    name: "Kanpur",
    slug: "kanpur",
    state: "Uttar Pradesh",
    region: "north",
    population: 2701324,
    volume: 3000,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim"],
    lat: 26.4499,
    lng: 80.3319,
  },
  {
    name: "Thane",
    slug: "thane",
    state: "Maharashtra",
    region: "west",
    population: 1886941,
    volume: 2800,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "christian"],
    lat: 19.2183,
    lng: 72.9781,
  },
  {
    name: "Allahabad",
    slug: "allahabad",
    state: "Uttar Pradesh",
    region: "north",
    population: 1168385,
    volume: 2600,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim"],
    lat: 25.4358,
    lng: 81.8463,
  },
  {
    name: "Bareilly",
    slug: "bareilly",
    state: "Uttar Pradesh",
    region: "north",
    population: 979533,
    volume: 1800,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim"],
    lat: 28.367,
    lng: 79.4304,
  },
  {
    name: "Jamnagar",
    slug: "jamnagar",
    state: "Gujarat",
    region: "west",
    population: 600943,
    volume: 1700,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "jain"],
    lat: 22.4707,
    lng: 70.0577,
  },
  {
    name: "Udaipur",
    slug: "udaipur",
    state: "Rajasthan",
    region: "north",
    population: 451100,
    volume: 2500,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "jain"],
    lat: 24.5854,
    lng: 73.7125,
  },
  {
    name: "Mangalore",
    slug: "mangalore",
    state: "Karnataka",
    region: "south",
    population: 499487,
    volume: 2200,
    priority: 50,
    tier: 3,
    tags: ["hindu", "christian", "muslim"],
    lat: 12.9141,
    lng: 74.856,
  },
  {
    name: "Shimla",
    slug: "shimla",
    state: "Himachal Pradesh",
    region: "north",
    population: 169578,
    volume: 1800,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "christian", "sikh"],
    lat: 31.1048,
    lng: 77.1734,
  },
  {
    name: "Dehradun",
    slug: "dehradun",
    state: "Uttarakhand",
    region: "north",
    population: 578420,
    volume: 2000,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "sikh"],
    lat: 30.3165,
    lng: 78.0322,
  },
  {
    name: "Bhubaneswar",
    slug: "bhubaneswar",
    state: "Odisha",
    region: "east",
    population: 837737,
    volume: 2300,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "christian"],
    lat: 20.2961,
    lng: 85.8245,
  },
  {
    name: "Siliguri",
    slug: "siliguri",
    state: "West Bengal",
    region: "east",
    population: 701489,
    volume: 1900,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "christian", "buddhist"],
    lat: 26.7271,
    lng: 88.3953,
  },
  {
    name: "Panaji",
    slug: "panaji",
    state: "Goa",
    region: "west",
    population: 114759,
    volume: 2000,
    priority: 50,
    tier: 3,
    tags: ["christian", "hindu", "muslim"],
    lat: 15.4909,
    lng: 73.8278,
  },
  {
    name: "Puducherry",
    slug: "puducherry",
    state: "Puducherry",
    region: "south",
    population: 244377,
    volume: 1600,
    priority: 50,
    tier: 3,
    tags: ["hindu", "christian", "muslim"],
    lat: 11.9416,
    lng: 79.8083,
  },
  {
    name: "Gangtok",
    slug: "gangtok",
    state: "Sikkim",
    region: "northeast",
    population: 100286,
    volume: 1400,
    priority: 50,
    tier: 3,
    tags: ["buddhist", "hindu", "christian"],
    lat: 27.3314,
    lng: 88.6138,
  },
  {
    name: "Shillong",
    slug: "shillong",
    state: "Meghalaya",
    region: "northeast",
    population: 143229,
    volume: 1500,
    priority: 50,
    tier: 3,
    tags: ["christian", "hindu", "muslim"],
    lat: 25.5788,
    lng: 91.8933,
  },
  {
    name: "Dimapur",
    slug: "dimapur",
    state: "Nagaland",
    region: "northeast",
    population: 122834,
    volume: 1300,
    priority: 50,
    tier: 3,
    tags: ["christian", "hindu", "muslim"],
    lat: 25.9092,
    lng: 93.7267,
  },
  {
    name: "Imphal",
    slug: "imphal",
    state: "Manipur",
    region: "northeast",
    population: 264986,
    volume: 1400,
    priority: 50,
    tier: 3,
    tags: ["hindu", "christian", "muslim"],
    lat: 24.817,
    lng: 93.9368,
  },
  {
    name: "Aizawl",
    slug: "aizawl",
    state: "Mizoram",
    region: "northeast",
    population: 293416,
    volume: 1300,
    priority: 50,
    tier: 3,
    tags: ["christian", "hindu", "muslim"],
    lat: 23.7271,
    lng: 92.7176,
  },
  {
    name: "Agartala",
    slug: "agartala",
    state: "Tripura",
    region: "northeast",
    population: 399688,
    volume: 1400,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "christian"],
    lat: 23.8315,
    lng: 91.2868,
  },
  {
    name: "Itanagar",
    slug: "itanagar",
    state: "Arunachal Pradesh",
    region: "northeast",
    population: 59490,
    volume: 1200,
    priority: 50,
    tier: 3,
    tags: ["buddhist", "christian", "hindu"],
    lat: 27.0844,
    lng: 93.6053,
  },
  {
    name: "Kohima",
    slug: "kohima",
    state: "Nagaland",
    region: "northeast",
    population: 115000,
    volume: 1200,
    priority: 50,
    tier: 3,
    tags: ["christian", "hindu"],
    lat: 25.6751,
    lng: 94.1086,
  },
  {
    name: "Port Blair",
    slug: "port-blair",
    state: "Andaman and Nicobar Islands",
    region: "south",
    population: 112050,
    volume: 1100,
    priority: 50,
    tier: 3,
    tags: ["hindu", "christian", "muslim", "sikh"],
    lat: 11.6234,
    lng: 92.7265,
  },
  {
    name: "Daman",
    slug: "daman",
    state: "Dadra and Nagar Haveli and Daman and Diu",
    region: "west",
    population: 114101,
    volume: 1000,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "christian"],
    lat: 20.3974,
    lng: 72.8328,
  },
  {
    name: "Leh",
    slug: "leh",
    state: "Ladakh",
    region: "north",
    population: 40000,
    volume: 1400,
    priority: 50,
    tier: 3,
    tags: ["buddhist", "muslim", "hindu"],
    lat: 34.1526,
    lng: 77.577,
  },
  {
    name: "Jammu",
    slug: "jammu",
    state: "Jammu and Kashmir",
    region: "north",
    population: 612000,
    volume: 2200,
    priority: 50,
    tier: 3,
    tags: ["hindu", "muslim", "sikh"],
    lat: 32.7266,
    lng: 74.857,
  },
];

const STATES = [
  {
    name: "Maharashtra",
    slug: "maharashtra",
    region: "west",
    volume: 25000,
    priority: 40,
    tags: ["hindu", "muslim", "buddhist", "christian", "jain"],
    lat: 19.7515,
    lng: 75.7139,
  },
  {
    name: "Uttar Pradesh",
    slug: "uttar-pradesh",
    region: "north",
    volume: 22000,
    priority: 40,
    tags: ["hindu", "muslim"],
    lat: 26.8467,
    lng: 80.9462,
  },
  {
    name: "Tamil Nadu",
    slug: "tamil-nadu",
    region: "south",
    volume: 18000,
    priority: 40,
    tags: ["hindu", "muslim", "christian"],
    lat: 11.1271,
    lng: 78.6569,
  },
  {
    name: "Karnataka",
    slug: "karnataka",
    region: "south",
    volume: 17000,
    priority: 40,
    tags: ["hindu", "muslim", "christian"],
    lat: 15.3173,
    lng: 75.7139,
  },
  {
    name: "Kerala",
    slug: "kerala",
    region: "south",
    volume: 16000,
    priority: 40,
    tags: ["hindu", "christian", "muslim"],
    lat: 10.8505,
    lng: 76.2711,
  },
  {
    name: "Gujarat",
    slug: "gujarat",
    region: "west",
    volume: 15000,
    priority: 40,
    tags: ["hindu", "muslim", "jain"],
    lat: 22.2587,
    lng: 71.1924,
  },
  {
    name: "Rajasthan",
    slug: "rajasthan",
    region: "north",
    volume: 14000,
    priority: 40,
    tags: ["hindu", "muslim", "jain"],
    lat: 27.0238,
    lng: 74.2179,
  },
  {
    name: "West Bengal",
    slug: "west-bengal",
    region: "east",
    volume: 15000,
    priority: 40,
    tags: ["hindu", "muslim", "christian", "buddhist"],
    lat: 22.9868,
    lng: 87.855,
  },
  {
    name: "Delhi",
    slug: "delhi",
    region: "north",
    volume: 20000,
    priority: 40,
    tags: ["hindu", "muslim", "sikh", "christian", "jain"],
    lat: 28.7041,
    lng: 77.1025,
  },
  {
    name: "Punjab",
    slug: "punjab",
    region: "north",
    volume: 12000,
    priority: 40,
    tags: ["sikh", "hindu", "muslim"],
    lat: 31.1471,
    lng: 75.3412,
  },
  {
    name: "Haryana",
    slug: "haryana",
    region: "north",
    volume: 11000,
    priority: 40,
    tags: ["hindu", "muslim", "sikh", "jain"],
    lat: 29.0588,
    lng: 76.0856,
  },
  {
    name: "Madhya Pradesh",
    slug: "madhya-pradesh",
    region: "central",
    volume: 10000,
    priority: 40,
    tags: ["hindu", "muslim", "jain", "buddhist"],
    lat: 22.9734,
    lng: 78.6569,
  },
  {
    name: "Bihar",
    slug: "bihar",
    region: "east",
    volume: 10000,
    priority: 40,
    tags: ["hindu", "muslim"],
    lat: 25.0961,
    lng: 85.3131,
  },
  {
    name: "Andhra Pradesh",
    slug: "andhra-pradesh",
    region: "south",
    volume: 9500,
    priority: 40,
    tags: ["hindu", "muslim", "christian"],
    lat: 15.9129,
    lng: 79.74,
  },
  {
    name: "Telangana",
    slug: "telangana",
    region: "south",
    volume: 9000,
    priority: 40,
    tags: ["hindu", "muslim"],
    lat: 18.1124,
    lng: 79.0193,
  },
  {
    name: "Odisha",
    slug: "odisha",
    region: "east",
    volume: 8500,
    priority: 40,
    tags: ["hindu", "christian", "muslim"],
    lat: 20.9517,
    lng: 85.0985,
  },
  {
    name: "Assam",
    slug: "assam",
    region: "northeast",
    volume: 8000,
    priority: 40,
    tags: ["hindu", "muslim", "christian"],
    lat: 26.2006,
    lng: 92.9376,
  },
  {
    name: "Jharkhand",
    slug: "jharkhand",
    region: "east",
    volume: 7500,
    priority: 40,
    tags: ["hindu", "muslim", "christian"],
    lat: 23.6102,
    lng: 85.2799,
  },
  {
    name: "Chhattisgarh",
    slug: "chhattisgarh",
    region: "central",
    volume: 7000,
    priority: 40,
    tags: ["hindu", "muslim", "christian"],
    lat: 21.2787,
    lng: 81.8661,
  },
  {
    name: "Uttarakhand",
    slug: "uttarakhand",
    region: "north",
    volume: 6500,
    priority: 40,
    tags: ["hindu", "muslim", "sikh"],
    lat: 30.0668,
    lng: 79.0193,
  },
  {
    name: "Himachal Pradesh",
    slug: "himachal-pradesh",
    region: "north",
    volume: 6000,
    priority: 40,
    tags: ["hindu", "muslim", "sikh", "christian", "buddhist"],
    lat: 31.1048,
    lng: 77.1734,
  },
  {
    name: "Goa",
    slug: "goa",
    region: "west",
    volume: 5500,
    priority: 40,
    tags: ["christian", "hindu", "muslim"],
    lat: 15.2993,
    lng: 74.124,
  },
  {
    name: "Jammu and Kashmir",
    slug: "jammu-and-kashmir",
    region: "north",
    volume: 6000,
    priority: 40,
    tags: ["muslim", "hindu", "sikh", "buddhist"],
    lat: 33.7782,
    lng: 76.5762,
  },
  {
    name: "Manipur",
    slug: "manipur",
    region: "northeast",
    volume: 3500,
    priority: 40,
    tags: ["hindu", "christian", "muslim"],
    lat: 24.6637,
    lng: 93.9063,
  },
  {
    name: "Meghalaya",
    slug: "meghalaya",
    region: "northeast",
    volume: 3000,
    priority: 40,
    tags: ["christian", "hindu", "muslim"],
    lat: 25.467,
    lng: 91.3662,
  },
  {
    name: "Nagaland",
    slug: "nagaland",
    region: "northeast",
    volume: 2800,
    priority: 40,
    tags: ["christian", "hindu", "muslim"],
    lat: 26.1584,
    lng: 94.5624,
  },
  {
    name: "Tripura",
    slug: "tripura",
    region: "northeast",
    volume: 2500,
    priority: 40,
    tags: ["hindu", "muslim", "christian"],
    lat: 23.9408,
    lng: 91.9882,
  },
  {
    name: "Sikkim",
    slug: "sikkim",
    region: "northeast",
    volume: 2000,
    priority: 40,
    tags: ["buddhist", "hindu", "christian"],
    lat: 27.533,
    lng: 88.5122,
  },
  {
    name: "Arunachal Pradesh",
    slug: "arunachal-pradesh",
    region: "northeast",
    volume: 2000,
    priority: 40,
    tags: ["buddhist", "christian", "hindu"],
    lat: 27.0704,
    lng: 93.6061,
  },
  {
    name: "Mizoram",
    slug: "mizoram",
    region: "northeast",
    volume: 2000,
    priority: 40,
    tags: ["christian", "hindu", "muslim"],
    lat: 23.1645,
    lng: 92.9376,
  },
  {
    name: "Chandigarh",
    slug: "chandigarh-ut",
    region: "north",
    volume: 5000,
    priority: 30,
    tags: ["hindu", "sikh", "muslim", "christian"],
    lat: 30.7333,
    lng: 76.7794,
  },
  {
    name: "Puducherry",
    slug: "puducherry-ut",
    region: "south",
    volume: 3000,
    priority: 30,
    tags: ["hindu", "christian", "muslim"],
    lat: 11.9416,
    lng: 79.8083,
  },
  {
    name: "Andaman and Nicobar Islands",
    slug: "andaman-nicobar",
    region: "south",
    volume: 2000,
    priority: 30,
    tags: ["hindu", "christian", "muslim", "sikh"],
    lat: 11.7401,
    lng: 92.6586,
  },
  {
    name: "Lakshadweep",
    slug: "lakshadweep",
    region: "south",
    volume: 1500,
    priority: 30,
    tags: ["muslim", "hindu", "christian"],
    lat: 10.5667,
    lng: 72.6417,
  },
  {
    name: "Ladakh",
    slug: "ladakh",
    region: "north",
    volume: 2000,
    priority: 30,
    tags: ["buddhist", "muslim", "hindu"],
    lat: 34.2268,
    lng: 77.5619,
  },
  {
    name: "Dadra and Nagar Haveli and Daman and Diu",
    slug: "dadra-nagar-haveli-daman-diu",
    region: "west",
    volume: 1200,
    priority: 30,
    tags: ["hindu", "muslim", "christian"],
    lat: 20.1809,
    lng: 73.0169,
  },
];

// ============================================================================
// TOPIC DATA — 12 rows
// ============================================================================

const TOPICS = [
  {
    name: "Wedding Invitations",
    slug: "wedding-invitations",
    pillar: "primary",
    desc: "Digital and printed wedding invitations, e-cards, video invites, save-the-dates, RSVP management",
    icon: "💌",
    volume: 50000,
    priority: 100,
  },
  {
    name: "Wedding Venues",
    slug: "wedding-venues",
    pillar: "supporting",
    desc: "Banquet halls, outdoor venues, destination weddings, palace venues, garden and beach weddings",
    icon: "🏛️",
    volume: 45000,
    priority: 90,
  },
  {
    name: "Wedding Planning",
    slug: "wedding-planning",
    pillar: "supporting",
    desc: "Complete wedding planning guides, checklists, budget planners, timelines, vendor coordination",
    icon: "📋",
    volume: 40000,
    priority: 85,
  },
  {
    name: "Bridal Fashion",
    slug: "bridal-fashion",
    pillar: "supporting",
    desc: "Wedding sarees, bridal lehengas, groom outfits, jewelry, accessories, designer wear",
    icon: "👗",
    volume: 35000,
    priority: 80,
  },
  {
    name: "Wedding Makeup",
    slug: "wedding-makeup",
    pillar: "supporting",
    desc: "Bridal makeup artists, mehendi, hair styling, pre-wedding beauty, grooming",
    icon: "💄",
    volume: 30000,
    priority: 75,
  },
  {
    name: "Wedding Photography",
    slug: "wedding-photography",
    pillar: "supporting",
    desc: "Wedding photographers, videographers, candid photography, pre-wedding shoots, albums",
    icon: "📸",
    volume: 28000,
    priority: 75,
  },
  {
    name: "Wedding Catering",
    slug: "wedding-catering",
    pillar: "supporting",
    desc: "Wedding caterers, menu planning, food stalls, live counters, dessert options",
    icon: "🍽️",
    volume: 25000,
    priority: 70,
  },
  {
    name: "Wedding Decorations",
    slug: "wedding-decorations",
    pillar: "supporting",
    desc: "Stage decoration, floral arrangements, lighting, theme decor, mandap decoration",
    icon: "🌺",
    volume: 22000,
    priority: 70,
  },
  {
    name: "Wedding Entertainment",
    slug: "wedding-entertainment",
    pillar: "supporting",
    desc: "DJs, live bands, choreographers, sangeet planners, anchors, folk performers",
    icon: "🎵",
    volume: 20000,
    priority: 65,
  },
  {
    name: "Wedding Rituals",
    slug: "wedding-rituals",
    pillar: "supporting",
    desc: "Mehendi, sangeet, haldi, reception, traditional customs, religious ceremonies",
    icon: "🪔",
    volume: 18000,
    priority: 65,
  },
  {
    name: "Wedding Gifts",
    slug: "wedding-gifts",
    pillar: "supporting",
    desc: "Wedding gift ideas, return gifts, trousseau, gift packaging, personalized gifts",
    icon: "🎁",
    volume: 15000,
    priority: 60,
  },
  {
    name: "Honeymoon Planning",
    slug: "honeymoon-planning",
    pillar: "supporting",
    desc: "Honeymoon destinations, packages, budget planning, travel tips, romantic getaways",
    icon: "✈️",
    volume: 20000,
    priority: 65,
  },
];

// ============================================================================
// SUBTOPIC DATA — 20 per topic × 12 topics = 240 rows
// ============================================================================

const SUBTOPICS_BY_TOPIC: Record<
  string,
  Array<{
    name: string;
    slug: string;
    modifier: string | null;
    culture: string | null;
    volume: number;
    priority: number;
  }>
> = {
  "wedding-invitations": [
    {
      name: "Digital Wedding Invitations",
      slug: "digital-invitations",
      modifier: null,
      culture: null,
      volume: 12000,
      priority: 100,
    },
    {
      name: "Video Wedding Invitations",
      slug: "video-invitations",
      modifier: null,
      culture: null,
      volume: 8000,
      priority: 95,
    },
    {
      name: "Luxury Wedding Cards",
      slug: "luxury-wedding-cards",
      modifier: "luxury",
      culture: null,
      volume: 5000,
      priority: 90,
    },
    {
      name: "Budget Wedding Invitations",
      slug: "budget-invitations",
      modifier: "affordable",
      culture: null,
      volume: 6000,
      priority: 85,
    },
    {
      name: "Eco-Friendly Wedding Cards",
      slug: "eco-friendly-cards",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Animated E-Invitations",
      slug: "animated-invitations",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Save the Date Cards",
      slug: "save-the-date",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 80,
    },
    {
      name: "RSVP Management",
      slug: "rsvp-management",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Multi-Language Wedding Invitations",
      slug: "multi-language-invitations",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 70,
    },
    {
      name: "Custom Wedding Card Designs",
      slug: "custom-designs",
      modifier: null,
      culture: null,
      volume: 4500,
      priority: 85,
    },
    {
      name: "Hindu Wedding Invitations",
      slug: "hindu-invitations",
      modifier: null,
      culture: "hindu",
      volume: 8000,
      priority: 90,
    },
    {
      name: "Muslim Wedding Invitations",
      slug: "muslim-invitations",
      modifier: null,
      culture: "muslim",
      volume: 6000,
      priority: 85,
    },
    {
      name: "Christian Wedding Invitations",
      slug: "christian-invitations",
      modifier: null,
      culture: "christian",
      volume: 4000,
      priority: 80,
    },
    {
      name: "Sikh Wedding Invitations",
      slug: "sikh-invitations",
      modifier: null,
      culture: "sikh",
      volume: 3000,
      priority: 75,
    },
    {
      name: "Traditional Wedding Cards",
      slug: "traditional-cards",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 80,
    },
    {
      name: "Modern Wedding Invitations",
      slug: "modern-invitations",
      modifier: null,
      culture: null,
      volume: 5500,
      priority: 85,
    },
    {
      name: "Wedding Invitation Wording",
      slug: "invitation-wording",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 75,
    },
    {
      name: "WhatsApp Wedding Invitations",
      slug: "whatsapp-invitations",
      modifier: null,
      culture: null,
      volume: 7000,
      priority: 90,
    },
    {
      name: "Wedding Invitation Etiquette",
      slug: "invitation-etiquette",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Same-Day Wedding Invitations",
      slug: "same-day-invitations",
      modifier: null,
      culture: null,
      volume: 2000,
      priority: 65,
    },
  ],
  "wedding-venues": [
    {
      name: "Banquet Halls",
      slug: "banquet-halls",
      modifier: null,
      culture: null,
      volume: 10000,
      priority: 100,
    },
    {
      name: "Outdoor Wedding Venues",
      slug: "outdoor-venues",
      modifier: null,
      culture: null,
      volume: 7000,
      priority: 90,
    },
    {
      name: "Destination Wedding Locations",
      slug: "destination-weddings",
      modifier: null,
      culture: null,
      volume: 8000,
      priority: 95,
    },
    {
      name: "Budget Wedding Venues",
      slug: "budget-venues",
      modifier: "affordable",
      culture: null,
      volume: 6000,
      priority: 85,
    },
    {
      name: "Luxury Palace Weddings",
      slug: "palace-weddings",
      modifier: "luxury",
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Garden Wedding Venues",
      slug: "garden-venues",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 80,
    },
    {
      name: "Beach Wedding Venues",
      slug: "beach-weddings",
      modifier: null,
      culture: null,
      volume: 4500,
      priority: 80,
    },
    {
      name: "Farmhouse Weddings",
      slug: "farmhouse-weddings",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Heritage Venue Weddings",
      slug: "heritage-venues",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 75,
    },
    {
      name: "Rooftop Wedding Venues",
      slug: "rooftop-venues",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Resort Wedding Venues",
      slug: "resort-weddings",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Hotel Wedding Venues",
      slug: "hotel-weddings",
      modifier: null,
      culture: null,
      volume: 6000,
      priority: 90,
    },
    {
      name: "Temple Wedding Venues",
      slug: "temple-weddings",
      modifier: null,
      culture: "hindu",
      volume: 3000,
      priority: 75,
    },
    {
      name: "Club Wedding Venues",
      slug: "club-venues",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 70,
    },
    {
      name: "Small Wedding Venues",
      slug: "small-venues",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Grand Wedding Venues",
      slug: "grand-venues",
      modifier: "luxury",
      culture: null,
      volume: 3000,
      priority: 75,
    },
    {
      name: "Wedding Venues with Accommodation",
      slug: "venues-with-stay",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Poolside Wedding Venues",
      slug: "poolside-venues",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 70,
    },
    {
      name: "Hill Station Wedding Venues",
      slug: "hill-station-venues",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 75,
    },
    {
      name: "Affordable Marriage Halls",
      slug: "affordable-halls",
      modifier: "affordable",
      culture: null,
      volume: 5000,
      priority: 85,
    },
  ],
  "wedding-planning": [
    {
      name: "Complete Wedding Planning Guide",
      slug: "complete-guide",
      modifier: null,
      culture: null,
      volume: 8000,
      priority: 100,
    },
    {
      name: "Wedding Budget Planning",
      slug: "budget-planning",
      modifier: "affordable",
      culture: null,
      volume: 7000,
      priority: 95,
    },
    {
      name: "Wedding Vendor Checklist",
      slug: "vendor-checklist",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Wedding Timeline",
      slug: "wedding-timeline",
      modifier: null,
      culture: null,
      volume: 6000,
      priority: 90,
    },
    {
      name: "Destination Wedding Planning",
      slug: "destination-planning",
      modifier: null,
      culture: null,
      volume: 4500,
      priority: 85,
    },
    {
      name: "Monsoon Wedding Planning",
      slug: "monsoon-wedding",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 75,
    },
    {
      name: "Winter Wedding Planning",
      slug: "winter-wedding",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 80,
    },
    {
      name: "Small Wedding Planning",
      slug: "small-wedding",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Grand Wedding Planning",
      slug: "grand-wedding",
      modifier: "luxury",
      culture: null,
      volume: 3000,
      priority: 75,
    },
    {
      name: "DIY Wedding Planning",
      slug: "diy-wedding",
      modifier: "affordable",
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Wedding Theme Ideas",
      slug: "theme-ideas",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Wedding Decoration Planning",
      slug: "decoration-planning",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Wedding Guest List Management",
      slug: "guest-list",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Wedding Catering Planning",
      slug: "catering-planning",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Wedding Photography Planning",
      slug: "photography-planning",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Wedding Entertainment Planning",
      slug: "entertainment-planning",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 70,
    },
    {
      name: "Hindu Wedding Planning",
      slug: "hindu-wedding-planning",
      modifier: null,
      culture: "hindu",
      volume: 5000,
      priority: 85,
    },
    {
      name: "Muslim Wedding Planning",
      slug: "muslim-wedding-planning",
      modifier: null,
      culture: "muslim",
      volume: 3500,
      priority: 80,
    },
    {
      name: "Christian Wedding Planning",
      slug: "christian-wedding-planning",
      modifier: null,
      culture: "christian",
      volume: 2500,
      priority: 70,
    },
    {
      name: "Sikh Wedding Planning",
      slug: "sikh-wedding-planning",
      modifier: null,
      culture: "sikh",
      volume: 2000,
      priority: 65,
    },
  ],
  "bridal-fashion": [
    {
      name: "Wedding Sarees",
      slug: "wedding-sarees",
      modifier: null,
      culture: null,
      volume: 10000,
      priority: 100,
    },
    {
      name: "Bridal Lehengas",
      slug: "bridal-lehengas",
      modifier: null,
      culture: null,
      volume: 9000,
      priority: 95,
    },
    {
      name: "Groom Wedding Outfits",
      slug: "groom-outfits",
      modifier: null,
      culture: null,
      volume: 7000,
      priority: 90,
    },
    {
      name: "Budget Bridal Wear",
      slug: "budget-bridal-wear",
      modifier: "affordable",
      culture: null,
      volume: 6000,
      priority: 85,
    },
    {
      name: "Luxury Wedding Attire",
      slug: "luxury-attire",
      modifier: "luxury",
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Reception Gowns",
      slug: "reception-gowns",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Wedding Jewelry",
      slug: "wedding-jewelry",
      modifier: null,
      culture: null,
      volume: 8000,
      priority: 90,
    },
    {
      name: "Bridal Accessories",
      slug: "bridal-accessories",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 75,
    },
    {
      name: "Pre-Wedding Outfit Ideas",
      slug: "pre-wedding-outfits",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Bridal Footwear",
      slug: "bridal-footwear",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "South Indian Bridal Wear",
      slug: "south-indian-bridal",
      modifier: null,
      culture: "hindu",
      volume: 5000,
      priority: 80,
    },
    {
      name: "North Indian Bridal Wear",
      slug: "north-indian-bridal",
      modifier: null,
      culture: "hindu",
      volume: 6000,
      priority: 85,
    },
    {
      name: "Bengali Bridal Fashion",
      slug: "bengali-bridal",
      modifier: null,
      culture: "hindu",
      volume: 3500,
      priority: 75,
    },
    {
      name: "Punjabi Bridal Fashion",
      slug: "punjabi-bridal",
      modifier: null,
      culture: "sikh",
      volume: 4000,
      priority: 80,
    },
    {
      name: "Designer Wedding Lehengas",
      slug: "designer-lehengas",
      modifier: "luxury",
      culture: null,
      volume: 4500,
      priority: 85,
    },
    {
      name: "Bridal Makeup Looks",
      slug: "bridal-makeup-looks",
      modifier: null,
      culture: null,
      volume: 5500,
      priority: 85,
    },
    {
      name: "Wedding Dress Shopping Guide",
      slug: "dress-shopping",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Bridal Fashion Trends",
      slug: "bridal-trends",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Plus Size Bridal Wear",
      slug: "plus-size-bridal",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 70,
    },
    {
      name: "Maternity Bridal Wear",
      slug: "maternity-bridal",
      modifier: null,
      culture: null,
      volume: 1500,
      priority: 60,
    },
  ],
  "wedding-makeup": [
    {
      name: "Bridal Makeup Artists",
      slug: "bridal-makeup-artists",
      modifier: null,
      culture: null,
      volume: 10000,
      priority: 100,
    },
    {
      name: "Pre-Wedding Beauty Treatments",
      slug: "pre-wedding-beauty",
      modifier: null,
      culture: null,
      volume: 6000,
      priority: 85,
    },
    {
      name: "Mehendi Artists",
      slug: "mehendi-artists",
      modifier: null,
      culture: null,
      volume: 7000,
      priority: 90,
    },
    {
      name: "Bridal Hair Styling",
      slug: "bridal-hair",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Groom Grooming",
      slug: "groom-grooming",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Budget Bridal Makeup",
      slug: "budget-makeup",
      modifier: "affordable",
      culture: null,
      volume: 5000,
      priority: 80,
    },
    {
      name: "HD Bridal Makeup",
      slug: "hd-bridal-makeup",
      modifier: "luxury",
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Airbrush Makeup",
      slug: "airbrush-makeup",
      modifier: "luxury",
      culture: null,
      volume: 2500,
      priority: 70,
    },
    {
      name: "Traditional Bridal Looks",
      slug: "traditional-bridal-looks",
      modifier: null,
      culture: null,
      volume: 4500,
      priority: 80,
    },
    {
      name: "Modern Bridal Makeup",
      slug: "modern-bridal-makeup",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "South Indian Bridal Makeup",
      slug: "south-indian-makeup",
      modifier: null,
      culture: "hindu",
      volume: 4000,
      priority: 80,
    },
    {
      name: "North Indian Bridal Makeup",
      slug: "north-indian-makeup",
      modifier: null,
      culture: "hindu",
      volume: 5000,
      priority: 85,
    },
    {
      name: "Bridal Skincare Routine",
      slug: "bridal-skincare",
      modifier: null,
      culture: null,
      volume: 4500,
      priority: 80,
    },
    {
      name: "Bridal Party Makeup",
      slug: "bridal-party-makeup",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Makeup Trial Guide",
      slug: "makeup-trial",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 65,
    },
    {
      name: "Bridal Beauty Packages",
      slug: "beauty-packages",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Natural Bridal Makeup",
      slug: "natural-makeup",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Bridal Makeup for Dark Skin",
      slug: "dark-skin-makeup",
      modifier: null,
      culture: null,
      volume: 2000,
      priority: 65,
    },
    {
      name: "Bridal Nail Art",
      slug: "bridal-nail-art",
      modifier: null,
      culture: null,
      volume: 1500,
      priority: 55,
    },
    {
      name: "Bridal Makeup Price Guide",
      slug: "makeup-prices",
      modifier: "affordable",
      culture: null,
      volume: 4000,
      priority: 75,
    },
  ],
  "wedding-photography": [
    {
      name: "Wedding Photographers",
      slug: "wedding-photographers",
      modifier: null,
      culture: null,
      volume: 10000,
      priority: 100,
    },
    {
      name: "Candid Wedding Photography",
      slug: "candid-photography",
      modifier: null,
      culture: null,
      volume: 7000,
      priority: 90,
    },
    {
      name: "Pre-Wedding Photoshoot",
      slug: "pre-wedding-shoot",
      modifier: null,
      culture: null,
      volume: 8000,
      priority: 95,
    },
    {
      name: "Wedding Videography",
      slug: "wedding-videography",
      modifier: null,
      culture: null,
      volume: 6000,
      priority: 85,
    },
    {
      name: "Drone Wedding Photography",
      slug: "drone-photography",
      modifier: "luxury",
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Wedding Albums",
      slug: "wedding-albums",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Traditional Wedding Photography",
      slug: "traditional-photography",
      modifier: null,
      culture: null,
      volume: 4500,
      priority: 80,
    },
    {
      name: "Budget Wedding Photography",
      slug: "budget-photography",
      modifier: "affordable",
      culture: null,
      volume: 5000,
      priority: 80,
    },
    {
      name: "Luxury Wedding Photography",
      slug: "luxury-photography",
      modifier: "luxury",
      culture: null,
      volume: 3000,
      priority: 75,
    },
    {
      name: "Wedding Photo Editing",
      slug: "photo-editing",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Wedding Cinematography",
      slug: "wedding-cinematography",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Same-Day Wedding Edit",
      slug: "same-day-edit",
      modifier: "luxury",
      culture: null,
      volume: 2500,
      priority: 70,
    },
    {
      name: "Wedding Photography Packages",
      slug: "photography-packages",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Wedding Photo Booth",
      slug: "wedding-photo-booth",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Post-Wedding Photoshoot",
      slug: "post-wedding-shoot",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Wedding Photography Trends",
      slug: "photography-trends",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 65,
    },
    {
      name: "Hindu Wedding Photography",
      slug: "hindu-wedding-photography",
      modifier: null,
      culture: "hindu",
      volume: 4500,
      priority: 80,
    },
    {
      name: "Muslim Wedding Photography",
      slug: "muslim-wedding-photography",
      modifier: null,
      culture: "muslim",
      volume: 3000,
      priority: 75,
    },
    {
      name: "Wedding Photographer Cost",
      slug: "photographer-cost",
      modifier: "affordable",
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Wedding Photography Checklist",
      slug: "photography-checklist",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
  ],
  "wedding-catering": [
    {
      name: "Wedding Caterers",
      slug: "wedding-caterers",
      modifier: null,
      culture: null,
      volume: 8000,
      priority: 100,
    },
    {
      name: "Wedding Menu Planning",
      slug: "menu-planning",
      modifier: null,
      culture: null,
      volume: 6000,
      priority: 90,
    },
    {
      name: "Wedding Food Stalls",
      slug: "food-stalls",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Live Food Counters",
      slug: "live-counters",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Wedding Dessert Options",
      slug: "dessert-options",
      modifier: null,
      culture: null,
      volume: 4500,
      priority: 85,
    },
    {
      name: "Vegetarian Wedding Catering",
      slug: "vegetarian-catering",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Non-Vegetarian Wedding Menu",
      slug: "non-veg-menu",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Budget Wedding Catering",
      slug: "budget-catering",
      modifier: "affordable",
      culture: null,
      volume: 5000,
      priority: 80,
    },
    {
      name: "Luxury Wedding Catering",
      slug: "luxury-catering",
      modifier: "luxury",
      culture: null,
      volume: 3000,
      priority: 75,
    },
    {
      name: "South Indian Wedding Food",
      slug: "south-indian-food",
      modifier: null,
      culture: "hindu",
      volume: 4000,
      priority: 80,
    },
    {
      name: "North Indian Wedding Food",
      slug: "north-indian-food",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Mughlai Wedding Menu",
      slug: "mughlai-menu",
      modifier: null,
      culture: "muslim",
      volume: 2500,
      priority: 70,
    },
    {
      name: "Wedding Cake",
      slug: "wedding-cake",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Wedding Cocktail Menu",
      slug: "cocktail-menu",
      modifier: "luxury",
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Wedding Catering Cost",
      slug: "catering-cost",
      modifier: "affordable",
      culture: null,
      volume: 4500,
      priority: 80,
    },
    {
      name: "Traditional Wedding Cuisine",
      slug: "traditional-cuisine",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Wedding Snacks and Appetizers",
      slug: "wedding-snacks",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Wedding Beverage Options",
      slug: "wedding-beverages",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 65,
    },
    {
      name: "Wedding Catering for 500 Guests",
      slug: "large-event-catering",
      modifier: null,
      culture: null,
      volume: 2000,
      priority: 65,
    },
    {
      name: "Halal Wedding Catering",
      slug: "halal-catering",
      modifier: null,
      culture: "muslim",
      volume: 2500,
      priority: 70,
    },
  ],
  "wedding-decorations": [
    {
      name: "Wedding Stage Decoration",
      slug: "stage-decoration",
      modifier: null,
      culture: null,
      volume: 8000,
      priority: 100,
    },
    {
      name: "Floral Wedding Decorations",
      slug: "floral-decorations",
      modifier: null,
      culture: null,
      volume: 7000,
      priority: 95,
    },
    {
      name: "Wedding Lighting Design",
      slug: "lighting-design",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Theme Wedding Decorations",
      slug: "theme-decorations",
      modifier: null,
      culture: null,
      volume: 6000,
      priority: 90,
    },
    {
      name: "Wedding Entrance Decor",
      slug: "entrance-decor",
      modifier: null,
      culture: null,
      volume: 4500,
      priority: 80,
    },
    {
      name: "Mandap Decoration",
      slug: "mandap-decoration",
      modifier: null,
      culture: "hindu",
      volume: 5500,
      priority: 85,
    },
    {
      name: "Wedding Backdrop Design",
      slug: "backdrop-design",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Budget Wedding Decorations",
      slug: "budget-decorations",
      modifier: "affordable",
      culture: null,
      volume: 5000,
      priority: 80,
    },
    {
      name: "Luxury Wedding Decorations",
      slug: "luxury-decorations",
      modifier: "luxury",
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Rustic Wedding Decor",
      slug: "rustic-decor",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Boho Wedding Decor",
      slug: "boho-decor",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 65,
    },
    {
      name: "Wedding Table Decoration",
      slug: "table-decoration",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Wedding Flower Arrangements",
      slug: "flower-arrangements",
      modifier: null,
      culture: null,
      volume: 4500,
      priority: 80,
    },
    {
      name: "Wedding Balloon Decor",
      slug: "balloon-decor",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 65,
    },
    {
      name: "Wedding Candle Decor",
      slug: "candle-decor",
      modifier: null,
      culture: null,
      volume: 2000,
      priority: 60,
    },
    {
      name: "Wedding Car Decoration",
      slug: "car-decoration",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Wedding Decoration Packages",
      slug: "decoration-packages",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Traditional Wedding Decor",
      slug: "traditional-decor",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Modern Wedding Decor",
      slug: "modern-decor",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Wedding Decoration Cost",
      slug: "decoration-cost",
      modifier: "affordable",
      culture: null,
      volume: 4000,
      priority: 80,
    },
  ],
  "wedding-entertainment": [
    {
      name: "Wedding DJs",
      slug: "wedding-djs",
      modifier: null,
      culture: null,
      volume: 7000,
      priority: 100,
    },
    {
      name: "Live Wedding Bands",
      slug: "live-bands",
      modifier: null,
      culture: null,
      volume: 5500,
      priority: 90,
    },
    {
      name: "Wedding Choreographers",
      slug: "choreographers",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Sangeet Planners",
      slug: "sangeet-planners",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Wedding Anchors and Emcees",
      slug: "wedding-anchors",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Folk Dance Performers",
      slug: "folk-performers",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Wedding Games and Activities",
      slug: "wedding-games",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 65,
    },
    {
      name: "Wedding Fireworks",
      slug: "wedding-fireworks",
      modifier: "luxury",
      culture: null,
      volume: 2000,
      priority: 60,
    },
    {
      name: "Wedding Photo Booth Rental",
      slug: "photo-booth-rental",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Wedding Magician",
      slug: "wedding-magician",
      modifier: null,
      culture: null,
      volume: 1500,
      priority: 55,
    },
    {
      name: "Dandiya and Garba Night",
      slug: "dandiya-garba",
      modifier: null,
      culture: "hindu",
      volume: 3000,
      priority: 70,
    },
    {
      name: "Bhangra Performers",
      slug: "bhangra-performers",
      modifier: null,
      culture: "sikh",
      volume: 2500,
      priority: 65,
    },
    {
      name: "Wedding Playlist Guide",
      slug: "wedding-playlist",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Wedding Entertainment Budget",
      slug: "entertainment-budget",
      modifier: "affordable",
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Kids Entertainment at Wedding",
      slug: "kids-entertainment",
      modifier: null,
      culture: null,
      volume: 2000,
      priority: 60,
    },
    {
      name: "Wedding Dance Performance",
      slug: "dance-performance",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Live Music for Wedding",
      slug: "live-music",
      modifier: null,
      culture: null,
      volume: 4500,
      priority: 85,
    },
    {
      name: "Wedding Sound System",
      slug: "sound-system",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Celebrity Performance Wedding",
      slug: "celebrity-performance",
      modifier: "luxury",
      culture: null,
      volume: 1500,
      priority: 60,
    },
    {
      name: "Wedding Night Entertainment",
      slug: "night-entertainment",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 65,
    },
  ],
  "wedding-rituals": [
    {
      name: "Mehendi Ceremony",
      slug: "mehendi-ceremony",
      modifier: null,
      culture: null,
      volume: 7000,
      priority: 100,
    },
    {
      name: "Sangeet Night",
      slug: "sangeet-night",
      modifier: null,
      culture: null,
      volume: 6500,
      priority: 95,
    },
    {
      name: "Haldi Ceremony",
      slug: "haldi-ceremony",
      modifier: null,
      culture: "hindu",
      volume: 6000,
      priority: 90,
    },
    {
      name: "Reception Planning",
      slug: "reception-planning",
      modifier: null,
      culture: null,
      volume: 5500,
      priority: 85,
    },
    {
      name: "Traditional Wedding Customs",
      slug: "traditional-customs",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Hindu Wedding Rituals",
      slug: "hindu-rituals",
      modifier: null,
      culture: "hindu",
      volume: 6000,
      priority: 90,
    },
    {
      name: "Muslim Wedding Ceremony",
      slug: "muslim-ceremony",
      modifier: null,
      culture: "muslim",
      volume: 4000,
      priority: 80,
    },
    {
      name: "Christian Wedding Ceremony",
      slug: "christian-ceremony",
      modifier: null,
      culture: "christian",
      volume: 3000,
      priority: 75,
    },
    {
      name: "Sikh Wedding Anand Karaj",
      slug: "sikh-anand-karaj",
      modifier: null,
      culture: "sikh",
      volume: 2500,
      priority: 70,
    },
    {
      name: "Bengali Wedding Rituals",
      slug: "bengali-rituals",
      modifier: null,
      culture: "hindu",
      volume: 3000,
      priority: 75,
    },
    {
      name: "South Indian Wedding Rituals",
      slug: "south-indian-rituals",
      modifier: null,
      culture: "hindu",
      volume: 4000,
      priority: 80,
    },
    {
      name: "Marathi Wedding Rituals",
      slug: "marathi-rituals",
      modifier: null,
      culture: "hindu",
      volume: 3000,
      priority: 75,
    },
    {
      name: "Gujarati Wedding Rituals",
      slug: "gujarati-rituals",
      modifier: null,
      culture: "hindu",
      volume: 3000,
      priority: 75,
    },
    {
      name: "Punjabi Wedding Rituals",
      slug: "punjabi-rituals",
      modifier: null,
      culture: "sikh",
      volume: 3500,
      priority: 80,
    },
    {
      name: "Rajasthani Wedding Rituals",
      slug: "rajasthani-rituals",
      modifier: null,
      culture: "hindu",
      volume: 2500,
      priority: 70,
    },
    {
      name: "Mangal Sutra Ceremony",
      slug: "mangal-sutra",
      modifier: null,
      culture: "hindu",
      volume: 3000,
      priority: 70,
    },
    {
      name: "Wedding Vows Guide",
      slug: "wedding-vows",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Ring Exchange Ceremony",
      slug: "ring-ceremony",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Wedding Blessings and Prayers",
      slug: "wedding-blessings",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 65,
    },
    {
      name: "Post-Wedding Rituals",
      slug: "post-wedding-rituals",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
  ],
  "wedding-gifts": [
    {
      name: "Wedding Gift Ideas",
      slug: "gift-ideas",
      modifier: null,
      culture: null,
      volume: 8000,
      priority: 100,
    },
    {
      name: "Wedding Return Gifts",
      slug: "return-gifts",
      modifier: null,
      culture: null,
      volume: 6000,
      priority: 90,
    },
    {
      name: "Wedding Trousseau Items",
      slug: "trousseau-items",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Personalized Wedding Gifts",
      slug: "personalized-gifts",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "Budget-Friendly Wedding Gifts",
      slug: "budget-gifts",
      modifier: "affordable",
      culture: null,
      volume: 4500,
      priority: 80,
    },
    {
      name: "Luxury Wedding Gifts",
      slug: "luxury-gifts",
      modifier: "luxury",
      culture: null,
      volume: 3000,
      priority: 75,
    },
    {
      name: "Cash Wedding Gifts",
      slug: "cash-gifts",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Gold Wedding Gifts",
      slug: "gold-gifts",
      modifier: "luxury",
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "Wedding Gift Wrapping",
      slug: "gift-wrapping",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 60,
    },
    {
      name: "Groom Gift Ideas",
      slug: "groom-gifts",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Bride Gift Ideas",
      slug: "bride-gifts",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Couple Wedding Gifts",
      slug: "couple-gifts",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 80,
    },
    {
      name: "DIY Wedding Gifts",
      slug: "diy-gifts",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 65,
    },
    {
      name: "Wedding Gift Registry",
      slug: "gift-registry",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Traditional Wedding Gifts by Culture",
      slug: "traditional-gifts",
      modifier: null,
      culture: null,
      volume: 2000,
      priority: 65,
    },
    {
      name: "Home Appliances Wedding Gifts",
      slug: "home-appliance-gifts",
      modifier: null,
      culture: null,
      volume: 2000,
      priority: 60,
    },
    {
      name: "Experience Wedding Gifts",
      slug: "experience-gifts",
      modifier: null,
      culture: null,
      volume: 1500,
      priority: 55,
    },
    {
      name: "Wedding Gift Etiquette",
      slug: "gift-etiquette",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 70,
    },
    {
      name: "Gift Cards for Wedding",
      slug: "gift-cards",
      modifier: null,
      culture: null,
      volume: 2000,
      priority: 60,
    },
    {
      name: "Favor Boxes and Return Gifts",
      slug: "favor-boxes",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
  ],
  "honeymoon-planning": [
    {
      name: "Honeymoon Destinations",
      slug: "honeymoon-destinations",
      modifier: null,
      culture: null,
      volume: 10000,
      priority: 100,
    },
    {
      name: "Budget Honeymoon Packages",
      slug: "budget-honeymoon",
      modifier: "affordable",
      culture: null,
      volume: 7000,
      priority: 90,
    },
    {
      name: "Luxury Honeymoon Packages",
      slug: "luxury-honeymoon",
      modifier: "luxury",
      culture: null,
      volume: 5000,
      priority: 85,
    },
    {
      name: "International Honeymoon Destinations",
      slug: "international-honeymoon",
      modifier: null,
      culture: null,
      volume: 6000,
      priority: 90,
    },
    {
      name: "India Honeymoon Destinations",
      slug: "india-honeymoon",
      modifier: null,
      culture: null,
      volume: 5500,
      priority: 85,
    },
    {
      name: "Beach Honeymoon Destinations",
      slug: "beach-honeymoon",
      modifier: null,
      culture: null,
      volume: 5000,
      priority: 80,
    },
    {
      name: "Hill Station Honeymoon",
      slug: "hill-station-honeymoon",
      modifier: null,
      culture: null,
      volume: 4500,
      priority: 80,
    },
    {
      name: "Honeymoon Travel Tips",
      slug: "honeymoon-tips",
      modifier: null,
      culture: null,
      volume: 4000,
      priority: 75,
    },
    {
      name: "Honeymoon Planning Timeline",
      slug: "honeymoon-timeline",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 70,
    },
    {
      name: "Romantic Honeymoon Ideas",
      slug: "romantic-honeymoon",
      modifier: null,
      culture: null,
      volume: 4500,
      priority: 80,
    },
    {
      name: "Honeymoon Budget Guide",
      slug: "honeymoon-budget",
      modifier: "affordable",
      culture: null,
      volume: 4000,
      priority: 75,
    },
    {
      name: "Honeymoon from Mumbai",
      slug: "honeymoon-from-mumbai",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Honeymoon from Delhi",
      slug: "honeymoon-from-delhi",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 70,
    },
    {
      name: "Honeymoon from Bengaluru",
      slug: "honeymoon-from-bengaluru",
      modifier: null,
      culture: null,
      volume: 2500,
      priority: 65,
    },
    {
      name: "Adventure Honeymoon",
      slug: "adventure-honeymoon",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Cultural Honeymoon",
      slug: "cultural-honeymoon",
      modifier: null,
      culture: null,
      volume: 2000,
      priority: 60,
    },
    {
      name: "All-Inclusive Honeymoon Packages",
      slug: "all-inclusive-honeymoon",
      modifier: null,
      culture: null,
      volume: 3500,
      priority: 75,
    },
    {
      name: "Honeymoon Photography",
      slug: "honeymoon-photography",
      modifier: null,
      culture: null,
      volume: 2000,
      priority: 60,
    },
    {
      name: "Honeymoon Packing List",
      slug: "honeymoon-packing",
      modifier: null,
      culture: null,
      volume: 3000,
      priority: 70,
    },
    {
      name: "Post-COVID Honeymoon Planning",
      slug: "post-covid-honeymoon",
      modifier: null,
      culture: null,
      volume: 1500,
      priority: 50,
    },
  ],
};

// ============================================================================
// MAIN SEED FUNCTION
// ============================================================================

async function seedLocations(): Promise<void> {
  console.log("\n📍 Seeding locations...");

  const allLocations = [
    ...TIER_1_CITIES.map((c) => ({
      name: c.name,
      slug: c.slug,
      type: "city" as const,
      parent_state: c.state,
      region: c.region,
      population: c.population,
      search_volume: c.volume,
      priority: c.priority,
      tier: c.tier,
      cultural_tags: c.tags,
      latitude: c.lat,
      longitude: c.lng,
    })),
    ...TIER_2_CITIES.map((c) => ({
      name: c.name,
      slug: c.slug,
      type: "city" as const,
      parent_state: c.state,
      region: c.region,
      population: c.population,
      search_volume: c.volume,
      priority: c.priority,
      tier: c.tier,
      cultural_tags: c.tags,
      latitude: c.lat,
      longitude: c.lng,
    })),
    ...TIER_3_CITIES.map((c) => ({
      name: c.name,
      slug: c.slug,
      type: "city" as const,
      parent_state: c.state,
      region: c.region,
      population: c.population,
      search_volume: c.volume,
      priority: c.priority,
      tier: c.tier,
      cultural_tags: c.tags,
      latitude: c.lat,
      longitude: c.lng,
    })),
    ...STATES.filter(
      (s) =>
        ![
          "Chandigarh",
          "Puducherry",
          "Andaman and Nicobar Islands",
          "Lakshadweep",
          "Ladakh",
          "Dadra and Nagar Haveli and Daman and Diu",
        ].includes(s.name),
    ).map((s) => ({
      name: s.name,
      slug: s.slug,
      type: "state" as const,
      parent_state: null,
      region: s.region,
      population: 0,
      search_volume: s.volume,
      priority: s.priority,
      tier: 4,
      cultural_tags: s.tags,
      latitude: s.lat,
      longitude: s.lng,
    })),
    ...STATES.filter((s) =>
      [
        "Chandigarh",
        "Puducherry",
        "Andaman and Nicobar Islands",
        "Lakshadweep",
        "Ladakh",
        "Dadra and Nagar Haveli and Daman and Diu",
      ].includes(s.name),
    ).map((s) => ({
      name: s.name,
      slug: s.slug,
      type: "union-territory" as const,
      parent_state: null,
      region: s.region,
      population: 0,
      search_volume: s.volume,
      priority: s.priority,
      tier: 4,
      cultural_tags: s.tags,
      latitude: s.lat,
      longitude: s.lng,
    })),
  ];

  for (const loc of allLocations) {
    const { error } = await supabase
      .from("wedding_locations")
      .upsert(loc as any, { onConflict: "slug", ignoreDuplicates: false });

    if (error) {
      console.error(`  ❌ ${loc.name}: ${error.message}`);
    } else {
      console.log(`  ✅ ${loc.name} (${loc.type}, tier ${loc.tier})`);
    }
  }

  // Verify count
  const { count } = await supabase
    .from("wedding_locations")
    .select("*", { count: "exact", head: true });
  console.log(`\n📊 Total locations seeded: ${count}`);
}

async function seedTopics(): Promise<void> {
  console.log("\n📂 Seeding topics...");

  for (const topic of TOPICS) {
    const { error } = await supabase.from("wedding_topics").upsert(
      {
        name: topic.name,
        slug: topic.slug,
        pillar_type: topic.pillar,
        description: topic.desc,
        icon: topic.icon,
        search_volume: topic.volume,
        priority: topic.priority,
      },
      { onConflict: "slug", ignoreDuplicates: false },
    );

    if (error) {
      console.error(`  ❌ ${topic.name}: ${error.message}`);
    } else {
      console.log(`  ✅ ${topic.name} (${topic.pillar})`);
    }
  }

  const { count } = await supabase
    .from("wedding_topics")
    .select("*", { count: "exact", head: true });
  console.log(`\n📊 Total topics seeded: ${count}`);
}

async function seedSubtopics(): Promise<void> {
  console.log("\n📑 Seeding subtopics...");

  // Fetch topics to map slug -> id
  const { data: topics } = await supabase
    .from("wedding_topics")
    .select("id, slug");

  if (!topics) {
    console.error("❌ Could not fetch topics");
    return;
  }

  const topicMap = new Map(topics.map((t) => [t.slug, t.id]));
  let total = 0;

  for (const [topicSlug, subtopics] of Object.entries(SUBTOPICS_BY_TOPIC)) {
    const topicId = topicMap.get(topicSlug);
    if (!topicId) {
      console.error(`  ❌ Topic not found: ${topicSlug}`);
      continue;
    }

    for (const sub of subtopics) {
      const { error } = await supabase.from("wedding_subtopics").upsert(
        {
          topic_id: topicId,
          name: sub.name,
          slug: sub.slug,
          search_modifier: sub.modifier,
          cultural_context: sub.culture,
          search_volume: sub.volume,
          priority: sub.priority,
        },
        { onConflict: "topic_id,slug", ignoreDuplicates: false },
      );

      if (error) {
        console.error(`  ❌ ${sub.name}: ${error.message}`);
      } else {
        total++;
      }
    }
    console.log(`  ✅ ${topicSlug}: ${subtopics.length} subtopics`);
  }

  console.log(`\n📊 Total subtopics seeded: ${total}`);
}

async function generateQueue(): Promise<void> {
  console.log("\n⚡ Generating content queue...");

  const { data, error } = await supabase.rpc("generate_initial_content_queue");

  if (error) {
    console.error(`❌ Queue generation failed: ${error.message}`);
    return;
  }

  console.log(`✅ Content queue generated: ${data} items`);

  // Verify queue stats
  const { data: stats } = await supabase.rpc("get_queue_statistics");
  console.log("\n📊 Queue statistics:");
  console.log(stats);
}

// ============================================================================
// RUN ALL
// ============================================================================

async function main() {
  console.log("🚀 WEDINVITER pSEO — Database Seed Script");
  console.log("=".repeat(50));

  // Check connection
  const { error: pingError } = await supabase
    .from("wedding_locations")
    .select("id", { count: "exact", head: true });
  if (pingError && pingError.code !== "PGRST116") {
    console.error(`❌ Database connection failed: ${pingError.message}`);
    process.exit(1);
  }
  console.log("✅ Database connected\n");

  await seedLocations();
  await seedTopics();
  await seedSubtopics();
  await generateQueue();

  console.log("\n" + "=".repeat(50));
  console.log("🎉 Seeding complete!");
  console.log("Run: SELECT * FROM get_queue_statistics(); to verify");
}

main().catch((err) => {
  console.error("❌ Fatal error:", err);
  process.exit(1);
});
