// ============================================================================
// WEDINVITER pSEO — Shared Page Component for All 12 Pillars
// ============================================================================
// All 12 dynamic routes import this file to avoid code duplication.
// Each route file is a 5-line wrapper that passes its pillar slug.
// ============================================================================

import { createPseoClient } from "@/lib/pseo/client";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { PageRenderer } from "@/components/pseo/PageRenderer";
import type { PublishedPage } from "@/lib/pseo/types";

const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "https://wedinviter.wasleen.com";

// ---------------------------------------------------------------------------
// Metadata Generator
// ---------------------------------------------------------------------------

/**
 * Generates SEO metadata for any pSEO page.
 * Called by generateMetadata() in each pillar route.
 */
export async function generatePseoMetadata(
  pillarSlug: string,
  params: Promise<{ location: string; subtopic: string }>,
): Promise<Metadata> {
  const { location, subtopic } = await params;
  const supabase = createPseoClient();

  const urlPath = `/${pillarSlug}/${location}/${subtopic}`;

  const { data: page } = await supabase
    .from("published_pages")
    .select("title, meta_description, published_at")
    .eq("url_path", urlPath)
    .single();

  if (!page) {
    return {};
  }

  return {
    title: page.title,
    description: page.meta_description || undefined,
    alternates: {
      canonical: `${SITE_URL}${urlPath}`,
    },
    openGraph: {
      title: page.title,
      description: page.meta_description || undefined,
      url: `${SITE_URL}${urlPath}`,
      type: "article",
      siteName: "WedInviter",
      locale: "en_IN",
      publishedTime: page.published_at,
    },
    twitter: {
      card: "summary_large_image",
      title: page.title,
      description: page.meta_description || undefined,
    },
    robots: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
    },
  };
}

// ---------------------------------------------------------------------------
// Page Component
// ---------------------------------------------------------------------------

/**
 * Fetches a published pSEO page from Supabase and renders it.
 * Used by all 12 pillar dynamic routes.
 *
 * @param pillarSlug - The pillar slug (e.g., "wedding-invitations")
 * @param params - Next.js route params (location, subtopic)
 */
export default async function PseoPage({
  pillarSlug,
  params,
}: {
  pillarSlug: string;
  params: Promise<{ location: string; subtopic: string }>;
}) {
  const { location, subtopic } = await params;
  const supabase = createPseoClient();

  const urlPath = `/${pillarSlug}/${location}/${subtopic}`;

  const { data: page } = await supabase
    .from("published_pages")
    .select("*")
    .eq("url_path", urlPath)
    .single();

  if (!page) {
    notFound();
  }

  return (
    <>
      <PageRenderer page={page as unknown as PublishedPage} />
    </>
  );
}

// ---------------------------------------------------------------------------
// ISR Configuration
// ---------------------------------------------------------------------------

/**
 * 24-hour ISR revalidation. Pages are regenerated by the hourly cron
 * via the /api/revalidate webhook, which busts the cache for specific URLs.
 * Use as: `export const revalidate = PSEO_REVALIDATE;` in route files.
 */
export const PSEO_REVALIDATE = 86400; // 24 hours in seconds
