// ============================================================================
// WEDINVITER pSEO — Shared TypeScript Types
// ============================================================================

/** Queue item fetched by the hourly generation job */
export interface PseoQueueItem {
  queue_id: number;
  location_name: string;
  location_slug: string;
  topic_name: string;
  topic_slug: string;
  subtopic_name: string | null;
  subtopic_slug: string | null;
  target_keyword: string;
  url_slug: string;
  priority_score: number;
  cultural_context: string | null;
}

/** Complete content generated by DeepSeek AI */
export interface GeneratedContent {
  title: string;
  meta_description: string;
  h1: string;
  intro: {
    hook: string;
    context: string;
    preview: string;
  };
  benefits: Array<{
    title: string;
    description: string;
    icon: string;
  }>;
  main_content: Array<{
    heading: string;
    content: string;
    subsections?: Array<{
      subheading: string;
      content: string;
    }>;
  }>;
  local_insights: {
    popular_venues?: string[];
    best_seasons?: string;
    average_costs?: string;
    cultural_customs?: string;
  };
  vendor_recommendations?: Array<{
    category: string;
    tips: string;
    price_range: string;
  }>;
  faqs: Array<{
    question: string;
    answer: string;
  }>;
  testimonials?: Array<{
    name: string;
    location: string;
    quote: string;
    rating: number;
  }>;
  pricing_table?: {
    packages: Array<{
      name: string;
      price: string;
      features: string[];
    }>;
  };
  cta: {
    heading: string;
    description: string;
    button_text: string;
    features: string[];
  };
  related_topics: Array<{
    title: string;
    url: string;
  }>;
}

/** 6-dimension quality scores */
export interface QualityScores {
  overall: number;
  location_specificity: number;
  cultural_relevance: number;
  actionability: number;
  readability: number;
  keyword_optimization: number;
  uniqueness: number;
}

/** Database row shape for published_pages */
export interface PublishedPage {
  id: number;
  queue_id: number;
  url_path: string;
  topic_slug: string;
  location_slug: string;
  subtopic_slug: string | null;
  title: string;
  meta_description: string | null;
  h1_heading: string | null;
  canonical_url: string | null;
  intro_section: GeneratedContent["intro"] | null;
  benefits: GeneratedContent["benefits"] | null;
  main_content: GeneratedContent["main_content"] | null;
  local_insights: GeneratedContent["local_insights"] | null;
  vendor_recommendations: GeneratedContent["vendor_recommendations"] | null;
  faqs: GeneratedContent["faqs"] | null;
  testimonials: GeneratedContent["testimonials"] | null;
  pricing_table: GeneratedContent["pricing_table"] | null;
  cta_section: GeneratedContent["cta"] | null;
  related_pages: GeneratedContent["related_topics"] | null;
  schema_json: Record<string, unknown> | null;
  quality_score: number | null;
  location_specificity_score: number | null;
  cultural_relevance_score: number | null;
  actionability_score: number | null;
  word_count: number | null;
  view_count: number;
  conversion_count: number;
  published_at: string;
  last_updated: string;
}

/** Location seed data shape */
export interface LocationSeed {
  name: string;
  slug: string;
  type: "city" | "state" | "union-territory";
  parent_state: string | null;
  region: string;
  population: number;
  search_volume: number;
  priority: number;
  tier: number;
  cultural_tags: string[];
  latitude: number;
  longitude: number;
}

/** Topic seed data shape */
export interface TopicSeed {
  name: string;
  slug: string;
  pillar_type: "primary" | "supporting";
  description: string;
  icon: string;
  search_volume: number;
  priority: number;
}

/** Subtopic seed data shape */
export interface SubtopicSeed {
  topic_slug: string;
  name: string;
  slug: string;
  search_modifier: string | null;
  cultural_context: string | null;
  search_volume: number;
  priority: number;
}

/** Log entry status types */
export type GenerationStatus =
  | "success"
  | "failed"
  | "timeout"
  | "low_quality"
  | "keyword_stuffing";
